# Generated by Django 5.1.7 on 2025-04-01 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('User Story', 'User Story'), ('Technical Task', 'Technical Task')], max_length=255)),
                ('date', models.DateField()),
                ('prio', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('toDo', 'To Do'), ('inProgress', 'In Progress'), ('awaitFeedback', 'Await Feedback'), ('done', 'Done')], default='toDo', max_length=20)),
                ('assigned_to', models.ManyToManyField(related_name='tasks', to='contacts_app.contact')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('unchecked', 'Unchecked')], default='unchecked', max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks_app.task')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'ordering': ['id'],
            },
        ),
    ]
